### ISSUE TITLE
Unable to get it working

### ISSUE THREAD

**Issue by lechen26** [martinb3-cookbooks/xmledit-cookbook#12]
HI
i must have missed something but i cannot update an xml file using this cookbook and i'm not sure why.
i have this xml file:
```xml
<?xml version="1.0"?>
<dir-configuration>
  <host>
    <ip>10.10.10.10</ip>
  </host>
</dir-configuration>
```

i have this part of code on one of my cookbooks:
```
include_recipe "xmledit"

xml_edit 'Update my.xml' do
  path '/tmp/my2.xml'
  target '/dir-configuratino/host/ip[text()=\'10.10.10.10\']'
  fragment '<ip>0.0.0.0</ip>'
  action :replace
end
```
when running the recipe, i expect it to update the ip address from 10.10.10.10 to 0.0.0.0
the only thing i can see on the log is skipped due to nothing. what am i missing?

these are the last lines from the log
```
  * xml_edit[Update my2.xml] action replace[2015-07-19T07:03:37+00:00] INFO: Processing xml_edit[Update my2.xml] action replace (myrecipe::partial line 4)
Recipe: <Dynamically Defined Resource>
  * file[Update my2.xml] action create[2015-07-19T07:03:37+00:00] INFO: Processing file[Update my2.xml] action create (......../xmledit/libraries/provider.rb line 152)
 (up to date)
 (up to date)
  * file[Update my.xml] action nothing[2015-07-19T07:03:37+00:00] INFO: Processing file[Update my.xml] action nothing (............../xmledit/libraries/provider.rb line 152)
 (skipped due to action :nothing)
```

any help will be appriciated.

10x!
Chen

**Comment by martinb3** [comment]
Hi there -- perhaps there's a typo in how you're spelling configuration?
  `target '/dir-configuratino/host/ip[text()=\'10.10.10.10\']'`

**Comment by lechen26** [comment]
thanks alot for your response!

you are right, i've wrote a type here when posting the question.
i've only tried to copy minimal example just to show my issue, but apparently my problem was xml with namespaces.
the original xml file was with namespaces and i was able to update it using the following target:  '//xmlns:server/xmlns:address' like in nokogiri examples.

i'm still unable to parse more complicated example. it will be help if you can see what have i missed....

i have a file with multiple namespaces, and i want to change a simple value from specific namespace.
```xml
<?xml version="1.0" encoding="UTF-8"?>
<app-configuration xmlns="http://www.temp.com/namespace/AppConfig">  
<full-configuration>
    <my-class>
      <enable>true</enable>
        <name>ApplicationClassifier</name>
        <configuration>
           <application xmlns="http://www.temp.com/namespace/ApplicationClassifier" >
               <name>appName</name>
           </application>
        </configuration>
     </my-class>
    <my-class>
      <enable>true</enable>
        <name>ApplicationDefinition</name>
        <configuration>
           <application xmlns="http://www.temp.com/namespace/ApplicationDefinition" >
               <name>appDef</name>
           </application>
        </configuration>
     </my-class>
</full-configuration>
```

as you can see there are multiple paragraph of "my-class", and im trying to update the name of the application of the class "ApplicationClassifier".
i was able to do so using the Nokogiri parse xml , just by providing the xmlns that im searching for, like:
```
 @doc=Nokogiri::XML(File.open("/tmp/my.xml"))
    app_name=@doc.at_xpath('//xmlns:name', 'xmlns' => "http://www.temp.com/namespace/ApplicationClassifier")
    app_name.content="myNewApp"
    File.open("/tmp/my.xml",'w') { |f| f.write(@doc) }
```
this will update "AppName" to "MyNewApp" within the "ApplicationClassifier".
how can i achieve the same with xml_edit?
i've tried with something like this with no luck:
```
xml_edit 'Update my.xml' do
  path '/tmp/my.xml'
 target: " '//xmlns:name', 'xmlns' => \"http://www.temp.com/namespace/ApplicationClassifier\"  "
  fragment '<name>MyNewApp</name>'
  action :replace
end
```


any help will be appriciated!
thanks alot

Chen

**Comment by martinb3** [comment]
Are you sure this is doing what you think? It looks like `at_xpath` takes multiple search parameters. Perhaps you're just matching on the first one, and the second one is returning no matches? As far as I can tell, it doesn't mean a logical AND:
```
app_name=@doc.at_xpath('//xmlns:name', 'xmlns' => "http://www.temp.com/namespace/ApplicationClassifier"
```

**Comment by martinb3** [comment]
According to the nokogiri docs I'm reading, that's equivalent to the union of these:
```
@doc.at_xpath('//xmlns:name')
@doc.at_xpath('xmlns' => "http://www.temp.com/namespace/ApplicationClassifier")
```

**Comment by martinb3** [comment]
This would make sense, as it means you're just matching the first occurrence. Can you try this and see what it does?
```
xml_edit 'Update my.xml' do
  path '/tmp/my.xml'
  target: '//xmlns:name'
  fragment '<name>MyNewApp</name>'
  action :replace
end
```

**Comment by lechen26** [comment]
hi Martin, thanks for your response, i really appriciate that!
i've tried your suggestion, actually it does nothing...  i assume it would
change all occurrence of the name nodes but it actually havent changed
anything. i guess cause it didnt know what to change?
i wonder if i can do it differently without specifying the xmlns uri, and
instead use another variable,i mean each alss defined like that:

 <my-class>
      <enable>true</enable>
        <name>ApplicationDefinition</name>
        <configuration>
           <application
xmlns="http://www.temp.com/namespace/ApplicationDefinition" >
               <name>appDef</name>
           </application>
        </configuration>
     </my-class>

as you can see besides the difference of the xmlns , the difference is also
the name of the class itself (as ApplicationDefinition).
i wonder if it can be parsed like target
'//my-class[name=ApplicationDefinition]/configuration/name'
just to find the right name i want to change...

thanks

Chen
