### ISSUE TITLE
Append to end and to begin.

### ISSUE THREAD

**Issue by marchenkov** [martinb3-cookbooks/xmledit-cookbook#17]
If I use append_if_missing new value is appended to the end if I have list with values (because you use node_parent.add_child()).

Can you add new action: append_first_if_missing (and use node_parent.prepend_child(), but not node_parent.add_child()).
```
xml_edit 'set foo to true' do
  path '/etc/application.xml'
  target '/config/foo[text()=\'false\']'
  fragment '<foo>true</foo>'
  action : append_first_if_missing
end
```
OR
You can create first: true as option that I can pass:
```
xml_edit 'set foo to true' do
  path '/etc/application.xml'
  target '/config/foo[text()=\'false\']'
  fragment '<foo>true</foo>'
  first True
  action : append_if_missing
end
```

I've prefer first variant with new action: append_first_if_missing.

Thanks.

**Comment by martinb3** [comment]
Hello! I released this in the latest version, using `prepend` as the parameter. Could you give it a try and let us know?

**Comment by marchenkov** [comment]
Hello. Cool. Thank you very much!!!

**Comment by marchenkov** [comment]
Hi. 
When you plan release on Chef Supermarket? 
https://supermarket.chef.io/cookbooks/xmledit - just now I see only 3.0.2. 
Thanks.

**Comment by marchenkov** [comment]
All work as I need. Thanks.

**Comment by martinb3** [comment]
@marchenkov It's been released to Supermarket just now. Thanks!
