### ISSUE TITLE
Insert xml after any element in needed order

### ISSUE THREAD

**Issue by marchenkov** [martinb3-cookbooks/xmledit-cookbook#18]
Hi.

Can you realize to add new element after 1 or for example after 3?

For example

`<modules>    
  <module>1</module>    
  <module>3</module>    
</modules>`

I need to insert after 1 and before 3.

Thanks.

**Comment by martinb3** [comment]
Hi there -- this looks possible. What XPath expression have you tried?

**Comment by marchenkov** [comment]
I'm not understand how realize this inserting.

**Comment by martinb3** [comment]
Hello! Can you show a before and after? I'm happy to help troubleshoot, but please show us what you have already tried too.

**Comment by martinb3** [comment]
Closing since I haven't gotten a response.

**Comment by marchenkov** [comment]
Example.

Input: <modules><module>1</module><module>3</module></modules> (I have 1,3).

I need insert after <module>1</module>, before <module>3</module> (must receive output
<modules><module>1</module><module>2</module><module>3</module></modules>
).

If I use append and prepend: false I receive: <modules><module>1</module><module>3</module><module>2</module></modules> - not correct order 1,3,2.

If I use append and prepend: true I receive: <modules><module>1</module><module>3</module><module>2</module></modules> - not correct order 2,1,3.

How I can receive 1,2,3 in correct order (append after 1 and before 3)?

**Comment by martinb3** [comment]
Please show us the exact chef code you've tried 👍

**Comment by marchenkov** [comment]
Input xml:
```
<?xml version="1.0" encoding="UTF-8"?>
<Root version="2">
  <Server>
    <Modules>
    </Modules>
  </Server>
</Root>
```

Input chef: 
 ```
include_recipe 'xmledit'

  xml_edit "test_append1" do
    path "/home/msasha/test.xml"
    parent '/Root/Server/Modules'
    target "/Root/Server/Modules/Module[Name=\'module1\']"
    fragment "<Module>
                <Name>module1</Name>
              </Module>"
    action :append_if_missing
  end

  xml_edit "test_append2" do
    path "/home/msasha/test.xml"
    parent '/Root/Server/Modules'
    target "/Root/Server/Modules/Module[Name=\'module2\']"
    fragment "<Module>
                <Name>module2</Name>
              </Module>"
    action :append_if_missing
  end

  xml_edit "test_append4" do
    path "/home/msasha/test.xml"
    parent '/Root/Server/Modules'
    target "/Root/Server/Modules/Module[Name=\'module4\']"
    fragment "<Module>
                <Name>module4</Name>
              </Module>"
    action :append_if_missing
  end

  xml_edit "test_append5" do
    path "/home/msasha/test.xml"
    parent '/Root/Server/Modules'
    target "/Root/Server/Modules/Module[Name=\'module5\']"
    fragment "<Module>
                <Name>module5</Name>
              </Module>"
    action :append_if_missing
  end
```

After execute I receive modules in order: module1, module2, module4, module5.
How I can insert next module after module2 and before module4?

Thanks

**Comment by martinb3** [comment]
Have you tried something like?
```
 xml_edit "test_append3" do
   path "/home/msasha/test.xml"
   parent '/Root/Server/Modules'
   target "/Root/Server/Modules/Module[Name=\'module2\']"
   fragment "<Module>
               <Name>module2</Name>
             </Module>
             <Module>
               <Name>module3</Name>
             </Module>"
   action :replace
 end
```

**Comment by marchenkov** [comment]
Martin - I've run 2 times chef-client and recive next:
every time that I run chef-client this changes applied.
module3  - 2 times and more....

`<?xml version="1.0" encoding="UTF-8"?>
<Root version="2">
  <Server>
    <Modules>
      <Module>
        <Name>module1</Name>
      </Module>
      <Module>
        <Name>module2</Name>
      </Module>
      <Module>
        <Name>module3</Name>
      </Module>
      <Module>
        <Name>module3</Name>
      </Module>
      <Module>
        <Name>module4</Name>
      </Module>
      <Module>
        <Name>module5</Name>
      </Module>
    </Modules>
  </Server>
</Root>`

**Comment by martinb3** [comment]
You probably need to add an `only_if` or `not_if` to that resource, to prevent insertion too many times, if you only want it to happen once.
